### ISSUE TITLE
DHS API Request Failed [500] 

### ISSUE THREAD

**Issue by skuchukh** [ropensci/rdhs#127]
Good afternoon 

An odd  new error starting coming up for me while using the RDHS package stating (see the screenshot below): 
-> DHS API Request Failed [500] 
 -> Error Type: dhs_internal_server_error

This only came up after I  tried to add individual male surveys to my analysis in addition to my existing female and biomarker surveys which I've been using successfully for months now. I'm wondering if this has something to do with the error but I  don't see a connection. 

Thank you in advance! 

```r

```
</details>
<img width="581" alt="Screen Shot 2021-12-17 at 1 03 36 AM" src="https://user-images.githubusercontent.com/70972181/146448637-479f9824-ef12-4dfc-8231-3ebf866a65c8.png">

**Comment by athowes** [comment]
I'm also getting this error (haven't changed anything about the scripts I'm running). I'd have guessed it doesn't have anything to do with adding individual male surveys to your analysis (or anything that's changed in my environment) and is a recent problem with the DHS API (if the error message is trustworthy).

```
Error in handle_api_response(resp, TRUE) : 
   -> DHS API Request Failed [500] 
   -> Error Type: dhs_internal_server_error
```

**Comment by skuchukh** [comment]
Thank you! 
It seems the issue has been resolved for me without taking any action.

**Comment by athowes** [comment]
I'm still getting this error, have tried refreshing my DHS credentials but hasn't helped so far.

**Comment by jeffeaton** [comment]
Can you give us the steps that result in this error so that we can try to reproduce this?

Thanks,
Jeff

**Comment by skuchukh** [comment]
Good afternoon, 
My code continues to work just fine; however previously the error would appear when calling the following, after completely quitting R (so when I  had to provide my DHS credentials). The credentials I  used were correct. 

`rm(list=ls()) #clears workspace
rdhs::set_rdhs_config(data_frame = "data.table::as.data.table",
                      email = toString("my email"),
                      project = "My project name",
                      config_path = "rdhs.json",
                      global = FALSE)`

Kind regards
Salome

**Comment by rlglaubius** [comment]
I was able to replicate this issue following steps from README.md below. The error occurred on the call to dhs_surveys; some of the earlier lines of code are likely unnecessary for the replication.

```
library(rdhs)
dhs_indicators(indicatorIds = "ML_PMAL_C_RDT", returnFields=c("IndicatorId", "ShortName"))
dhs_data(countryIds = c("CD","TZ"), indicatorIds = "ML_PMAL_C_RDT", surveyYearStart = 2013, returnFields=c("Indicator", "SurveyId", "Value", "SurveyYearLabel", "CountryName"))
sc <- dhs_survey_characteristics()
sc[grepl("Malaria", sc$SurveyCharacteristicName), ]
ids <- dhs_countries(returnFields=c("CountryName", "DHS_CountryCode"))
survs <- dhs_surveys(surveyCharacteristicIds = 89, countryIds = c("CD","TZ"), surveyYearStart = 2013)
```

**Comment by jeffeaton** [comment]
Thanks @rlglaubius. I reproduce that error and have stepped through it. It looks like the DHS API `surveys` endpoint is down. Browsing to it through web browser gives me the same error as @skuchukh and @athowes report above: https://api.dhsprogram.com/rest/dhs/surveys

<img width="718" alt="image" src="https://user-images.githubusercontent.com/7427899/147016566-ec195fc9-74d1-4298-ab0a-66d64d3c1e89.png">

This might be a question for Trevor. @OJWatson -- any other suggestions?

Thanks,
Jef

**Comment by jeffeaton** [comment]
Hi all -- DHS have got the surveys API endpoint up and working again. This should be resolved now. Let us know if any further issues.

Thanks,
Jeff

**Comment by athowes** [comment]
![image](https://user-images.githubusercontent.com/29818116/167405991-07c429e8-1db6-409f-951b-536f221df326.png)

Same issue is back for me.

**Comment by jeffeaton** [comment]
Hmmm -- I just tried that endpoint and it has worked okay for me:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/7427899/167435937-c3a34031-9620-45c6-b46a-57a87fa79b55.png">

Can you try one more time and see if back up for you?
