### ISSUE TITLE
unzip() fails for >4GB files: India 2015 IR and HR datasets

### ISSUE THREAD

**Issue by jeffeaton** [ropensci/rdhs#43]
Not really sure what we should do about this one!! Are there other `unzip()` options?

```
> get_datasets("IAIR74FL.ZIP")
Downloading: 
India 2015 DHS Individual Recode Flat ASCII data (.dat) [IAIR74FL.ZIP]
Error in unzip(zfile, file[1], exdir = tmp) : 
  (converted from warning) possible truncation of >= 4GB file

> get_datasets("IAHR74FL.ZIP")
Downloading: 
India 2015 DHS Household Recode Flat ASCII data (.dat) [IAHR74FL.ZIP]
Error in unzip(zfile, file[1], exdir = tmp) : 
  (converted from warning) possible truncation of >= 4GB file
```

**Comment by jeffeaton** [comment]
Using the system `unzip` resolves this for my Mac so that I can get the India 2015 datasets, but I suspect this solution is not robust cross platform. 

Implemented here: a91cfc1

**Comment by richfitz** [comment]
My suggested solution:

- wrap unzip in a function within the package
- check `file.size` of the input zip and if <4GB then just keep going with `utils::unzip`
- if it's bigger than unzip, then do `Sys.which("unzip")` to see if `unzip` can be found
- if it's not found (use `nzchar()` on the output of above) throw an error (not a bloody warning)
- if it is found then pass the path found above in as the `unzip = ` argument to `utils::unzip`

**Comment by OJWatson** [comment]
this is in now as `unzip_special`,   however i'm struggling to test that this works as i think i hit RAM issues first with iotools handling the file rather than with the unzip (so probably is fine then)

**Comment by jeffeaton** [comment]
Thanks, I’ll have a look and test on my computer.

I suspect it is possible with `iotools` to process the data files in batches for very large files. I’ll try to have a look.


On 18 Jul 2018, at 23:08, OJ Watson <notifications@github.com<mailto:notifications@github.com>> wrote:


this is in now as unzip_special, however i'm struggling to test that this works as i think i hit RAM issues first with iotools handling the file rather than with the unzip (so probably is fine then)

**Comment by sakrejda** [comment]
I ran into this as well.  If adding the BH/Rcpp packages as a dependency is an option I can add a short c++ function that would use a cross platform streaming (zipped file -> unzipped file) method with very low memory overhead and no file size limit (in practical terms).     This could all be optional (so check file size prior to unzip and check for rcpp/BH before trying).

**Comment by OJWatson** [comment]
Hey,

This could work nicely. We have some tools in place already for when you decide how you want to convert your api data frames, e.g. to a `data.table`, that means that we don't have to import data.table as a package. So we could do something similar and then the user can say what unzip function they would like to provide.

I'll have a look at this and see if this approach will work with Rcpp too,

**Comment by sakrejda** [comment]
Ok, thanks. Let me know how it looks.

**Comment by sakrejda** [comment]
@OJWatson bump.

So, uh, looks like R itself shells out to run 'unzip'.... in this [file](https://github.com/wch/r-source/blob/5a156a0865362bb8381dcd69ac335f5174a4f60c/src/library/utils/R/zip.R) you can see the `system2` calls... :/

**Comment by OJWatson** [comment]
This would explain why `unzip_special` does nothing... 

Okay will have a think. I really don't want to have to depend on BH so will try and put in a "specify your own zip function" argument in the config bit. Won't be for a while as i'm semi swamped and need to respond to other things.

1 of those other things is responding to comments on rdhs so you'll be happy to know your "rdhs.json" in a different directory issue will be coming in.

**Comment by jeffeaton** [comment]
OJ,
What about perhaps seeing if @richfitz might be able to help out with this one? It would be nice to be able to support the India surveys at release.

Agree, should try hard to avoid BH dependency...

Thanks,
Jeff


On Sep 26, 2018, at 00:43, OJ Watson <notifications@github.com<mailto:notifications@github.com>> wrote:


This would explain why unzip_special does nothing...

Okay will have a think. I really don't want to have to depend on BH so will try and put in a "specify your own zip function" argument in the config bit. This won't be for a while as i'm semi swamped and need to respond to other things including reviewer comments about rdhs for Ropensci. However, you'll be happy to know your "rdhs.json" in a different directory issue will be coming in with these fixes. Should be done by end of today

**Comment by richfitz** [comment]
So, that function does not _always_ call the system zip. If `method = "internal"` (which is the default) then an internal unzip is used

```
   unzip: The method to be used.  An alternative is to use
          ‘getOption("unzip")’, which on a Unix-alike may be set to the
          path to a ‘unzip’ program.
```

though from the source code itself it looks like it will shell out to unzip if needed.  It also looks like the docs about `getOption("unzip")` are possibly incorrect as there's no use of `getOption` within the function itself. So:

1. Find a 4GB file
2. Confirm that `unzip(thatfile)` fails
3. See how `unzip(thatfile, method = Sys.which("unzip"))` works
4. Write some wrapper code that switches on `file.size(thatfile)` including some error checking if a suitable `unzip` is not found on the path

**Comment by richfitz** [comment]
One can also just extract the pieces of BH that support the unzipping, after confirming that works with >4GB files

**Comment by sakrejda** [comment]
Or just borrow R's code and switch it to the streaming mode, that's more irritating to code but not impossible: https://github.com/wch/r-source/blob/5a156a0865362bb8381dcd69ac335f5174a4f60c/src/main/dounzip.c#L306

**Comment by OJWatson** [comment]
Hey, so I just checked again and `unzip_special` is doing what you've bulleted out Rich, but i was a mug and was checking file size on the zip rather than the contents. Have amended and it now works fine for me to download and unzip the file. 

However, it won't actually read the file in with `iotools` due to memory issues:

```
 get_datasets("IAIR74FL.ZIP")
Downloading: 
India 2015 DHS Individual Recode Flat ASCII data (.dat) [IAIR74FL.ZIP]
Error: cannot allocate vector of size 2.7 Mb
> traceback()
8: formatter(readBin(input, what = "raw", n = n), ...)
7: readfn(unzip_special(zfile, file[1], exdir = tmp), ...) at read_datasets.R#331
6: read_zipdata(zfile, "\\.DAT$", iotools::input.file, formatter = iotools::dstrfw, 
       col_types = dct$col_types, widths = dct$len, strict = FALSE) at read_dhs_flat.R#341
5: read_dhs_flat(file, all_lower = all_lower, ...) at read_datasets.R#61
4: read_dhs_dataset(zip_path, dataset = desired_dataset, reformat, 
       all_lower, ...) at authentication.R#327
3: download_datasets(config = private$config, desired_dataset = datasets[i, 
       ], output_dir_root = output_dir_root, download_option = download_option, 
       all_lower = all_lower, reformat = reformat, ...) at client.R#396
2: client$get_datasets(dataset_filenames, download_option = download_option, 
       reformat = reformat, all_lower = all_lower, output_dir_root = output_dir_root, 
       clear_cache = clear_cache, ...) at ui.R#128
1: get_datasets("IAIR74FL.ZIP")
```

if you set your `memory.limit()` to seriously large though it will work so i am closing this.

**Comment by OJWatson** [comment]
Reopened due to email request. Code with error:

```

> get_datasets("IAIR74FL.ZIP")
Downloading:
India 2015 DHS Individual Recode Flat ASCII data (.dat) [IAIR74FL.ZIP]
Error: vector memory exhausted (limit reached?)
In addition: Warning message:
In unzip(zipfile = zipfile, files = files, overwrite = overwrite,  :
  possible truncation of >= 4GB file
> traceback()
7: mapply(FUN = f, ..., SIMPLIFY = FALSE)
6: Map("attr<-", dat[dct$name], "label", dct$label)
5: read_dhs_flat(file, all_lower = all_lower, ...)
4: read_dhs_dataset(zip_path, dataset = desired_dataset, reformat,
       all_lower, ...)
3: download_datasets(config = private$config, desired_dataset = datasets[i,
       ], output_dir_root = output_dir_root, download_option = download_option,
       all_lower = all_lower, reformat = reformat, ...)
2: client$get_datasets(dataset_filenames, download_option = download_option,
       reformat = reformat, all_lower = all_lower, output_dir_root = output_dir_root,
       clear_cache = clear_cache, ...)
1: get_datasets("IAIR74FL.ZIP")
```

**Comment by m-maheu-giroux** [comment]
@OJWatson, any update on this?
Thanks a lot in advance!

**Comment by OJWatson** [comment]
Hey @m-maheu-giroux, 

Sorry for the delay - PhD got in the way bit have now finished and have had a look at it. 

Sadly, still don't have a positive outcome. There was an error in `unzip_special` that meant it wasn't being triggered when the file was greater than 40Gb rather than 4Gb. I have fixed that locally but it then it throws an error later when trying to actually read in the unzipped file due to memory limits. I only have 16Gb RAM and I hit that limit when trying to read the survey file.

I will push the changes to `unzip_special` shortly with a few other changes so if you have more RAM than I do you can give it a go and fingers crossed it will still work. Otherwise I am out of ideas.

Sorry it's not a positive answer at the moment - @jeffeaton any other ideas?

OJ

**Comment by m-maheu-giroux** [comment]
Could I manually download that specific large file directly form DHS in flat format and find away to convert it to .rds (what function should I use, if any) and put it in the relevant folder?

M

**Comment by jeffeaton** [comment]
Hi,

Is the error occurring during unzipping the file, or during some further processing step?  Perhaps we could process lines of the text file in batches to reduce memory requirements.

Thanks,
Jeff

On 21 Oct 2019, at 16:28, OJ Watson <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @m-maheu-giroux<https://github.com/m-maheu-giroux>,

Sorry for the delay - PhD got in the way bit have now finished and have had a look at it.

Sadly, still don't have a positive outcome. There was an error in unzip_special that meant it wasn't being triggered when the file was greater than 40Gb rather than 4Gb. I have fixed that locally but it then it throws an error later when trying to actually read in the unzipped file due to memory limits. I only have 16Gb RAM and I hit that limit when trying to read the survey file.

I will push the changes to unzip_special shortly with a few other changes so if you have more RAM than I do you can give it a go and fingers crossed it will still work. Otherwise I am out of ideas.

Sorry it's not a positive answer at the moment - @jeffeaton<https://github.com/jeffeaton> any other ideas?

OJ

**Comment by OJWatson** [comment]
Sorry if i've clearly been unclear. The file downloads fine. And also can be unzipped fine. The error occurs now later within `read_dhs_flat`. Or rather my RAM runs out during this and not during the unzip bit (once you make sure that `unzip_special` uses the system unzip for files greater than 4e9).

**Comment by OJWatson** [comment]
So the batch idea might have to be used. However, i'm currently rerunning it to find out the exact bit it runs out on. give it a bit

**Comment by OJWatson** [comment]
Okay have rerun. The vast majority of RAM went on the first line below. And then it crashed R when trying to map the label attributes. 

```
dat <- read_zipdata(
    zfile, "\\.DAT$", iotools::input.file, formatter = iotools::dstrfw,
    col_types = dct$col_types, widths = dct$len, strict = FALSE
  )
names(dat) <- dct$name
dat[dct$name] <- Map("attr<-", dat[dct$name], "label", dct$label)
```

**Comment by jeffeaton** [comment]
That line `dat[dct$name] <- Map("attr<-", dat[dct$name], "label", dct$label)` might be extremely memory inefficient. It might be doing 1 or more full copies. Simply `for` looping over that might solve the problem.


On 21 Oct 2019, at 17:45, OJ Watson <notifications@github.com<mailto:notifications@github.com>> wrote:


Okay have rerun. The vast majority of RAM went on the first line below. And then it crashed R when trying to map the label attributes.

dat <- read_zipdata(
    zfile, "\\.DAT$", iotools::input.file, formatter = iotools::dstrfw,
    col_types = dct$col_types, widths = dct$len, strict = FALSE
  )
names(dat) <- dct$name
dat[dct$name] <- Map("attr<-", dat[dct$name], "label", dct$label)

**Comment by OJWatson** [comment]
True - however, i think the issue is that the raw data is 13558914432 bytes, i.e. 13.6 Gb, as it's a data.frame of 699686 x 4796 dimensions...

So I "think" with the changes about to be pushed, as long as you have 32Gb RAM you should be okay. But it hopefully will work. May also though change it to a loop.

**Comment by OJWatson** [comment]
@m-maheu-giroux Quick update - sorry for the delay in pulling in the development branch. Have just moved to the states starting my post-doc so have been getting set up but will find sometime to bring it in so hopefully you can read the data set in.

**Comment by saranyaprakash2012** [comment]
Hi, 
I am using rdhs for a statistics project and it is very useful. I am hitting the same 4GB issue discussed here on the India HR dataset (2015). wondering if there is a workaround I could follow to continue using the file 

Downloading: 
India 2015 DHS Household Recode Flat ASCII data (.dat) [IAHR74FL.ZIP]
Logging into DHS website...
Dataset download finished
Warning message:
In unzip(zipfile = zipfile, files = files, overwrite = overwrite,  :
  possible truncation of >= 4GB file
>

**Comment by jeffeaton** [comment]
Hello,

I believe that this is fixed in the Github version of the package (v0.7.0) but not yet the CRAN released version (v0.6.3).  

Could you try installing the Github version and see if this persists?

```
#install.packages("devtools")
devtools::install_github("ropensci/rdhs")
```

If it does not work with the Github version 0.7.0, could you please post the code, error message, and output of `sessionInfo()` ?

Thanks,
Jeff

**Comment by OJWatson** [comment]
Fixed in #95

**Comment by jwilliamrozelle** [comment]
I am still getting this issue in github version 0.7.6 for IA7. India 2020 DHS Individual Recode Stata dataset (.dta) [IAIR7DDT.ZIP]
Error in unzip_special(zfile, file[1], exdir = tmp) : 
  IAIR7DDT.ZIP is too large to unzip and a suitable unzip can not be found on your system.
